-- ============================================================
-- PLACE XP — CANONICAL SCHEMA
-- ============================================================
-- This file is the source of truth for what the database SHOULD
-- look like. It was generated by reading every `.from('table')`
-- call in the codebase (app/, components/, lib/) so it matches
-- the code exactly, not the other way around.
--
-- HOW TO USE THIS FILE
--  - Fresh Supabase project: paste this whole file into the SQL
--    Editor and run it once. It creates everything from scratch.
--  - Existing project (your current, manually-edited database):
--    do NOT run this file directly — it will fail on tables that
--    already exist. Instead run the incremental migrations in
--    order: step5 → step6 → security-fix → step7 → step8 → step9 →
--    step11. Those are additive/idempotent and safe against a live
--    database. Once applied, your database matches this file.
--
-- Every `create table` below uses `if not exists` and every
-- `create policy` is preceded by `drop policy if exists`, so this
-- file is also safe to re-run on an already-migrated database if
-- you ever want to sanity-check it hasn't drifted again.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- TABLES
-- ------------------------------------------------------------

-- One row per auth.users row. Created automatically by the
-- handle_new_user() trigger below when someone signs up.
create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  full_name   text,
  email       text,
  reg_no      text,
  department  text,
  year        text,
  section     text,
  phone       text,
  role        text not null default 'student'
              check (role in ('student', 'organizer', 'admin')),
  created_at  timestamptz not null default now()
);

create table if not exists public.events (
  id                      uuid primary key default gen_random_uuid(),
  slug                    text not null unique,
  title                   text not null,
  category                text,
  short_description       text,
  description             text,
  objectives              text,
  speaker_info            text,
  venue                   text,
  event_date              date,
  event_time              text,
  registration_deadline   timestamptz,
  seats_total             integer,
  banner_url              text,
  status                  text not null default 'upcoming'
                          check (status in ('upcoming', 'ongoing', 'past')),
  published               boolean not null default true,
  archived                boolean not null default false,
  rules                   text,
  requirements            text,
  created_by              uuid references public.profiles (id) on delete set null,
  created_at              timestamptz not null default now()
);

create index if not exists events_status_idx on public.events (status);
create index if not exists events_created_by_idx on public.events (created_by);

-- Pre-approval list for admin signups (see step11-admin-allowlist.sql).
-- Not reachable from the app/API — RLS on, zero policies, only the
-- SQL Editor / dashboard can touch it.
create table if not exists public.admin_allowlist (
  email       text primary key,
  added_at    timestamptz not null default now()
);

create table if not exists public.event_timeline (
  id          uuid primary key default gen_random_uuid(),
  event_id    uuid not null references public.events (id) on delete cascade,
  step_name   text not null,
  step_order  integer not null default 0,
  status      text not null default 'upcoming'
              check (status in ('upcoming', 'current', 'done'))
);

create index if not exists event_timeline_event_id_idx on public.event_timeline (event_id);

create table if not exists public.registrations (
  id                  uuid primary key default gen_random_uuid(),
  event_id            uuid not null references public.events (id) on delete cascade,
  user_id             uuid not null references public.profiles (id) on delete cascade,
  full_name           text,
  reg_no              text,
  email               text,
  phone               text,
  department          text,
  year                text,
  section             text,
  -- Added for the admin Registrations page. Defaults preserve the
  -- previous behaviour for every row inserted by existing code.
  payment_status      text not null default 'not_required'
                      check (payment_status in ('not_required', 'pending', 'paid', 'waived')),
  attendance_status   text not null default 'registered'
                      check (attendance_status in ('registered', 'attended', 'no_show')),
  approval_status     text not null default 'approved'
                      check (approval_status in ('pending', 'approved', 'rejected')),
  registered_at       timestamptz not null default now(),
  unique (event_id, user_id) -- RegistrationModal relies on the 23505 error code for "already registered"
);

create index if not exists registrations_event_id_idx on public.registrations (event_id);
create index if not exists registrations_user_id_idx on public.registrations (user_id);

create table if not exists public.announcements (
  id          uuid primary key default gen_random_uuid(),
  event_id    uuid not null references public.events (id) on delete cascade,
  title       text not null,
  content     text,
  created_by  uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now()
);

create index if not exists announcements_event_id_idx on public.announcements (event_id);

create table if not exists public.resources (
  id            uuid primary key default gen_random_uuid(),
  event_id      uuid not null references public.events (id) on delete cascade,
  title         text not null,
  file_url      text not null,
  file_type     text,
  uploaded_by   uuid references public.profiles (id) on delete set null,
  uploaded_at   timestamptz not null default now()
);

create index if not exists resources_event_id_idx on public.resources (event_id);

create table if not exists public.meeting_links (
  id          uuid primary key default gen_random_uuid(),
  event_id    uuid not null references public.events (id) on delete cascade,
  title       text not null,
  platform    text,
  url         text not null
);

create index if not exists meeting_links_event_id_idx on public.meeting_links (event_id);

create table if not exists public.faqs (
  id            uuid primary key default gen_random_uuid(),
  event_id      uuid not null references public.events (id) on delete cascade,
  question      text not null,
  answer        text not null,
  order_index   integer not null default 0
);

create index if not exists faqs_event_id_idx on public.faqs (event_id);

create table if not exists public.event_organizers (
  id          uuid primary key default gen_random_uuid(),
  event_id    uuid not null references public.events (id) on delete cascade,
  name        text not null,
  photo_url   text,
  position    text,
  email       text,
  phone       text,
  linkedin    text
);

create index if not exists event_organizers_event_id_idx on public.event_organizers (event_id);

create table if not exists public.tasks (
  id          uuid primary key default gen_random_uuid(),
  event_id    uuid references public.events (id) on delete set null,
  title       text not null,
  description text,
  status      text not null default 'todo'
              check (status in ('todo', 'in_progress', 'done')),
  priority    text not null default 'medium'
              check (priority in ('low', 'medium', 'high')),
  created_by  uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists tasks_event_id_idx on public.tasks (event_id);
create index if not exists tasks_status_idx on public.tasks (status);

create table if not exists public.site_settings (
  id            text primary key default 'site_settings',
  site_name     text not null default 'Place XP',
  contact_email text,
  instagram_url text,
  linkedin_url  text,
  x_url         text,
  updated_at    timestamptz not null default now()
);

create or replace function public.touch_site_settings_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists site_settings_touch_updated_at on public.site_settings;
create trigger site_settings_touch_updated_at
  before update on public.site_settings
  for each row execute function public.touch_site_settings_updated_at();

-- ------------------------------------------------------------
-- FUNCTIONS + TRIGGERS
-- ------------------------------------------------------------

-- security definer so RLS policies (below) can call this without
-- recursing back into the profiles policy that calls it.
create or replace function public.is_staff()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('organizer', 'admin')
  );
$$;

-- Checks admin_allowlist to decide the starting role (see
-- step11-admin-allowlist.sql) — everyone else still starts as
-- 'student'. Only an existing staff member can promote anyone after
-- that (see prevent_role_self_escalation below).
create or replace function public.handle_new_user()
returns trigger as $$
declare
  initial_role text := 'student';
begin
  if new.email !~* '@vitstudent\.ac\.in$' then
    raise exception 'Only VIT student email addresses (@vitstudent.ac.in) can sign up.';
  end if;

  if exists (select 1 from public.admin_allowlist where email = new.email) then
    initial_role := 'admin';
  end if;

  insert into public.profiles (id, full_name, email, reg_no, department, year, section, phone, role)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'reg_no',
    new.raw_user_meta_data->>'department',
    new.raw_user_meta_data->>'year',
    new.raw_user_meta_data->>'section',
    new.raw_user_meta_data->>'phone',
    initial_role
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Belt-and-braces: even if someone finds a way around the client
-- and issues a raw update to profiles, they still can't hand
-- themselves admin/organizer access. Only an existing staff member
-- (updating someone else, e.g. via the Supabase dashboard or a
-- future admin tool) can change a role.
create or replace function public.prevent_role_self_escalation()
returns trigger as $$
begin
  if new.role is distinct from old.role and not public.is_staff() then
    new.role := old.role;
  end if;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists profiles_prevent_role_escalation on public.profiles;
create trigger profiles_prevent_role_escalation
  before update on public.profiles
  for each row execute function public.prevent_role_self_escalation();

-- Participants can INSERT their own registration, but they should
-- never be able to mark themselves paid/attended/approved. Staff
-- (who use the admin Registrations page) are unaffected.
create or replace function public.enforce_registration_defaults()
returns trigger as $$
begin
  if not public.is_staff() then
    new.payment_status := 'not_required';
    new.attendance_status := 'registered';
    new.approval_status := 'approved';
  end if;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists registrations_enforce_defaults on public.registrations;
create trigger registrations_enforce_defaults
  before insert on public.registrations
  for each row execute function public.enforce_registration_defaults();

-- ------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ------------------------------------------------------------
-- Identical to step8-rls-policies.sql (that file is the one you
-- run against your existing database — this copy is here so a
-- fresh install from this single file is fully secured too).

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.event_timeline enable row level security;
alter table public.registrations enable row level security;
alter table public.announcements enable row level security;
alter table public.resources enable row level security;
alter table public.meeting_links enable row level security;
alter table public.faqs enable row level security;
alter table public.event_organizers enable row level security;

-- RLS on, deliberately zero policies attached: nothing reaches this
-- table through the app or API, only the SQL Editor / dashboard
-- (which connects as the database owner and bypasses RLS).
alter table public.admin_allowlist enable row level security;

-- profiles: everyone can read their own row; staff can read every row.
-- Only the owner can update it, and the role-escalation trigger above
-- stops a non-staff owner from changing their own role.
drop policy if exists "profiles select own or staff" on public.profiles;
create policy "profiles select own or staff" on public.profiles
  for select using (id = auth.uid() or public.is_staff());

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles
  for update using (id = auth.uid() or public.is_staff());

-- events: public sees published+non-archived events; staff sees all.
drop policy if exists "public read events" on public.events;
drop policy if exists "public read published events" on public.events;
create policy "public read published events" on public.events
  for select using ((published = true and archived = false) or public.is_staff());

drop policy if exists "staff write events" on public.events;
create policy "staff write events" on public.events
  for all using (public.is_staff()) with check (public.is_staff());

-- Per-event detail tables (timeline, announcements, resources, meeting
-- links, faqs, organizers): visible to staff, and to a participant who
-- is registered for that event — matches the participant Event
-- Dashboard, which only queries these after a successful registration.
do $$
declare
  t text;
begin
  foreach t in array array['event_timeline','announcements','resources','meeting_links','faqs','event_organizers']
  loop
    execute format('drop policy if exists "read if staff or registered" on public.%I', t);
    execute format($f$
      create policy "read if staff or registered" on public.%I
        for select using (
          public.is_staff()
          or exists (
            select 1 from public.registrations r
            where r.event_id = %I.event_id and r.user_id = auth.uid()
          )
        )
    $f$, t, t);

    execute format('drop policy if exists "staff write" on public.%I', t);
    execute format('create policy "staff write" on public.%I for all using (public.is_staff()) with check (public.is_staff())', t);
  end loop;
end $$;

-- registrations: a participant can see/insert only their own rows;
-- staff can see and manage every row (Registrations admin page).
drop policy if exists "registrations select own or staff" on public.registrations;
create policy "registrations select own or staff" on public.registrations
  for select using (user_id = auth.uid() or public.is_staff());

drop policy if exists "registrations insert own" on public.registrations;
create policy "registrations insert own" on public.registrations
  for insert with check (user_id = auth.uid() or public.is_staff());

drop policy if exists "registrations staff update" on public.registrations;
create policy "registrations staff update" on public.registrations
  for update using (public.is_staff()) with check (public.is_staff());

drop policy if exists "registrations staff delete" on public.registrations;
create policy "registrations staff delete" on public.registrations
  for delete using (public.is_staff());

-- ------------------------------------------------------------
-- STORAGE (event banners + event resource files)
-- ------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('event-banners', 'event-banners', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('event-resources', 'event-resources', true)
on conflict (id) do nothing;

drop policy if exists "public read event-banners" on storage.objects;
create policy "public read event-banners" on storage.objects
  for select using (bucket_id = 'event-banners');

drop policy if exists "staff write event-banners" on storage.objects;
create policy "staff write event-banners" on storage.objects
  for all using (bucket_id = 'event-banners' and public.is_staff())
  with check (bucket_id = 'event-banners' and public.is_staff());

drop policy if exists "public read event-resources" on storage.objects;
create policy "public read event-resources" on storage.objects
  for select using (bucket_id = 'event-resources');

drop policy if exists "staff write event-resources" on storage.objects;
create policy "staff write event-resources" on storage.objects
  for all using (bucket_id = 'event-resources' and public.is_staff())
  with check (bucket_id = 'event-resources' and public.is_staff());
