'use client';
import { useEffect, useState } from 'react';
import { CalendarCheck, CheckCircle2, Clock, X } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import RecruitmentClosedModal from '@/components/sections/RecruitmentClosedModal';
import type { EventSlot } from '@/types/database';

export default function SlotBookingClient({ deadline, whatsapp }: { deadline: string | null; whatsapp?: string | null }) {
  const db=createClient(); const closed=!deadline||new Date(deadline)<=new Date(); const [showClosed,setShowClosed]=useState(closed); const [slots,setSlots]=useState<EventSlot[]>([]); const [selected,setSelected]=useState<EventSlot|null>(null); const [message,setMessage]=useState('');
  async function load(){const {data}=await db.from('event_slots').select('*').is('event_id',null).order('slot_date').order('start_time');setSlots((data??[]) as EventSlot[])}
  useEffect(()=>{void load();const ch=db.channel('standalone-slots').on('postgres_changes',{event:'*',schema:'public',table:'event_slots'},load).subscribe();return()=>{void db.removeChannel(ch)}},[]);
  async function book(){if(!selected)return;const {error}=await db.rpc('book_event_slot',{p_slot_id:selected.id});setMessage(error?error.message:'Your slot has been booked successfully.');setSelected(null);if(!error)void load()}
  return <div className="space-y-6"><div className="flex gap-5 text-xs"><span className="text-emerald-400">● Available</span><span className="text-red-400">● Booked</span></div><div className="grid grid-cols-2 md:grid-cols-3 gap-4">{slots.map(s=><button disabled={closed||!!s.booked_by} key={s.id} onClick={()=>setSelected(s)} className={`rounded-2xl p-5 border text-center transition hover:-translate-y-0.5 ${s.booked_by?'bg-red-500/20 border-red-500/40 text-red-300':'bg-emerald-500/20 border-emerald-500/40 text-emerald-300 hover:bg-emerald-500/30'} disabled:opacity-50`}><Clock className="mx-auto mb-2 h-5 w-5"/><div>{s.start_time.slice(0,5)} - {s.end_time.slice(0,5)}</div><div className="text-xs mt-1">{s.slot_date}</div></button>)}</div>{!slots.length&&<p className="text-text-muted">No slots have been added yet.</p>}{message&&<div className="rounded-xl border border-orange-500/30 bg-orange-500/10 p-4 text-orange-300 flex gap-2"><CheckCircle2 className="h-5 w-5"/>{message}</div>}{whatsapp&&<a className="block rounded-xl border border-border-default bg-bg-elevated/40 px-4 py-3 text-orange-400 hover:bg-orange-500/10" href={whatsapp} target="_blank" rel="noreferrer">WhatsApp Group link</a>}{selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-5"><div className="w-full max-w-md rounded-3xl border border-orange-500/30 bg-bg-card p-7 shadow-2xl"><div className="flex items-start justify-between"><div><div className="mb-3 inline-flex rounded-xl bg-orange-500/15 p-3 text-orange-400"><CalendarCheck className="h-6 w-6"/></div><h2 className="text-2xl font-semibold text-text-primary">Confirm your slot</h2></div><button onClick={()=>setSelected(null)} aria-label="Close" className="text-text-muted hover:text-white"><X/></button></div><p className="mt-4 text-text-secondary">Are you sure you want to book this slot?</p><div className="mt-5 rounded-xl bg-bg-elevated p-4 text-center"><p className="font-medium text-text-primary">{selected.slot_date}</p><p className="mt-1 text-orange-400">{selected.start_time.slice(0,5)} – {selected.end_time.slice(0,5)}</p></div><div className="mt-6 flex gap-3"><button onClick={()=>void book()} className="flex-1 rounded-xl gradient-cta py-3 text-sm font-semibold text-white">Confirm booking</button><button onClick={()=>setSelected(null)} className="rounded-xl border border-border-default px-5 py-3 text-sm text-text-secondary">Cancel</button></div></div></div>}{showClosed&&<RecruitmentClosedModal title="Slot Booking Closed" description="The slot booking deadline has passed. You will be redirected to the homepage." onClose={()=>{window.location.href='/'}}/>}</div>
}
